user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

ticket:
    resource: "@TicketBundle/Resources/config/routing.yml"
    prefix:   /

#start:
#    resource: "@StartBundle/Resources/config/routing.yml"
#    prefix:   /start/
