custom_mailer:
    resource: "@CustomMailerBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

ticket:
    resource: "@TicketBundle/Resources/config/routing.yml"
    prefix:   /