security:
    encoders:
        UserBundle\Entity\user: bcrypt


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        orm_users:
            entity: { class: UserBundle:user, property: username }

    #    in_memory:
    #        memory:
    #            users:
    #                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
    #                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    #                a:     { password: a, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: user_login_check
                login_path: user_login_form
            logout:
                path:   logout
                target: ticketcrud_firstindex      #route for landing on homepage after logIN (what in the actual fuck)

            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: /register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: ROLE_USER }
