<?php

namespace UserBundle\Repository;

/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use UserBundle\Entity\user;

class userRepository extends \Doctrine\ORM\EntityRepository {

    public function findUser(user $user) {
        return $this->createQueryBuilder('u')
            ->andWhere('u = :inputUserId')
            ->setParameter('inputUserId', $user->getId())
            ->getQuery()
            ->execute();
    }

}
