<?php

namespace TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ticketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ticketRepository extends EntityRepository {

    public function findAllTicketsAdmin(){
        $this->findAll();
    }

    public function findAllTicketsUser() {

    }

    public function findAllTicketsProject() {
        //todo in future, where orm will have project entity
    }

    public function testFind(){
        return $this->createQueryBuilder('t')
            ->addOrderBy('t.time', 'ASC')
            ->andWhere('t.time > :now')
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->execute();
    }


    public function findAllTicketsUpcoming() {

    }

    public function findAllTicketsOverdue() {

    }

    public function findAllTicketsUpcomingSorted() {

    }

    public function findAllTicketsOverdueSorted() {

    }

}
